"""Portfolio Promotion Lab v1 governance thresholds."""

from __future__ import annotations


EVALUATION_WINDOWS = [
    30,
    60,
    90,
    180,
]

MIN_HISTORY_DAYS = 180
MIN_VALID_WINDOWS = 3

TRADING_DAYS_PER_YEAR = 365

TRANSACTION_COST_BPS = 10.0

MIN_WINDOW_WIN_RATE = 0.75
MIN_NET_RETURN_ADVANTAGE = 0.01
MIN_SHARPE_ADVANTAGE = 0.10
MIN_DRAWDOWN_IMPROVEMENT = 0.02

MAX_CANDIDATE_DRAWDOWN = 0.35
MAX_CANDIDATE_VOLATILITY = 0.75
MAX_ASSET_WEIGHT = 0.40
MIN_CASH_WEIGHT = 0.10

MAX_PROMOTION_TURNOVER = 0.85
MAX_CONCENTRATION_HHI = 0.30
MIN_EFFECTIVE_ASSET_COUNT = 3.0
