"""Compiled analytical artifact layer for Atlas."""

from atlas.compiled.compiler_identity import (
    COMPILER_NAME,
    COMPILER_VERSION,
    CompilerIdentity,
    build_compiler_identity,
    current_git_commit,
)
from atlas.compiled.calibration import (
    CALIBRATION_STATISTICS_SCHEMA,
    CALIBRATION_VECTORS_SCHEMA,
    DEFAULT_CALIBRATION_DIR,
    DEFAULT_CALIBRATION_VECTORS_PATH,
    DEFAULT_FEATURE_STATISTICS_PATH,
    CalibrationStatisticsArtifact,
    CalibrationVectorArtifact,
    FeatureStatistics,
    build_calibration_statistics,
    build_calibration_vector_artifact,
    build_feature_statistics,
    compiled_profile_keys,
    group_key,
    iter_compiled_calibration_vectors,
    load_calibration_statistics,
    load_calibration_vectors,
    load_calibration_vectors_from_artifacts,
    normalize_feature_from_statistics,
    save_calibration_statistics,
    save_calibration_vectors,
    source_manifest_hash,
)
from atlas.compiled.hashing import sha256_file
from atlas.compiled.identity_vector_artifact import (
    COMPILED_IDENTITY_VECTOR_SCHEMA,
    CompiledIdentityVectorArtifact,
)
from atlas.compiled.identity_vector_compiler import (
    compile_identity_vector_artifact,
    source_acf_path_for_profile,
)
from atlas.compiled.identity_vector_library_compiler import (
    EXPECTED_VECTOR_COUNT,
    LibraryCompilationResult,
    ProfileCompilationOutcome,
    compile_identity_vector_library,
    list_compilable_profile_keys,
    storage_reduction_ratio,
)
from atlas.compiled.identity_vector_store import (
    DEFAULT_COMPILED_VECTOR_DIR,
    artifact_path_for_profile,
    compiled_artifact_is_current,
    load_compiled_identity_vector,
    save_compiled_identity_vector,
)
from atlas.compiled.manifest import (
    COMPILED_MANIFEST_SCHEMA,
    DEFAULT_MANIFEST_PATH,
    CompilationManifest,
    build_compilation_manifest,
    save_compilation_manifest,
)

__all__ = [
    "CALIBRATION_STATISTICS_SCHEMA",
    "CALIBRATION_VECTORS_SCHEMA",
    "COMPILED_IDENTITY_VECTOR_SCHEMA",
    "COMPILED_MANIFEST_SCHEMA",
    "COMPILER_NAME",
    "COMPILER_VERSION",
    "CalibrationStatisticsArtifact",
    "CalibrationVectorArtifact",
    "CompilationManifest",
    "CompiledIdentityVectorArtifact",
    "CompilerIdentity",
    "DEFAULT_CALIBRATION_DIR",
    "DEFAULT_CALIBRATION_VECTORS_PATH",
    "DEFAULT_COMPILED_VECTOR_DIR",
    "DEFAULT_FEATURE_STATISTICS_PATH",
    "DEFAULT_MANIFEST_PATH",
    "EXPECTED_VECTOR_COUNT",
    "FeatureStatistics",
    "LibraryCompilationResult",
    "ProfileCompilationOutcome",
    "artifact_path_for_profile",
    "build_calibration_statistics",
    "build_calibration_vector_artifact",
    "build_compilation_manifest",
    "build_compiler_identity",
    "build_feature_statistics",
    "compile_identity_vector_artifact",
    "compile_identity_vector_library",
    "compiled_artifact_is_current",
    "compiled_profile_keys",
    "current_git_commit",
    "group_key",
    "iter_compiled_calibration_vectors",
    "list_compilable_profile_keys",
    "load_calibration_statistics",
    "load_calibration_vectors",
    "load_calibration_vectors_from_artifacts",
    "load_compiled_identity_vector",
    "normalize_feature_from_statistics",
    "save_calibration_statistics",
    "save_calibration_vectors",
    "save_compilation_manifest",
    "save_compiled_identity_vector",
    "sha256_file",
    "source_acf_path_for_profile",
    "source_manifest_hash",
    "storage_reduction_ratio",
]
