"""Identity Vector Engine public API."""

from atlas.ive.composite import (
    PLANET_ORDER,
    build_composite_planet_vector,
    build_composite_planet_vectors,
    composite_vectors_to_feature_table,
    ordered_planets,
)
from atlas.ive.feature_vector import (
    build_layer_vector_features,
    build_planet_feature_vector,
)
from atlas.ive.identity_vector import (
    build_identity_diagnostics,
    build_identity_global_features,
    build_identity_quality,
    build_identity_vector,
    build_raw_vectors_from_acf,
    ordered_planet_vectors,
)
from atlas.ive.normalizer import (
    DEFAULT_NORMALIZATION_MODE,
    comparable_vectors,
    minmax_scale,
    normalize_feature_value,
    normalize_planet_vector,
    normalize_planet_vectors,
    percentile_rank,
    zscore_to_unit,
)
from atlas.ive.relationship_matrix import (
    PlanetRelationshipMatrix,
    build_planet_relationship_matrix,
    relationship_matrix_to_dict,
    validate_relationship_matrix,
)
from atlas.ive.schema import (
    IDENTITY_GLOBAL_FEATURES,
    IVE_VERSION,
    VECTOR_FEATURES,
    CompositePlanetVector,
    IdentityVector,
    NormalizedPlanetVector,
    PlanetFeatureVector,
    composite_planet_vector_to_dict,
    identity_vector_to_dict,
    normalized_planet_vector_to_dict,
    planet_feature_vector_to_dict,
    validate_composite_vector,
    validate_feature_vector,
    validate_identity_vector,
    validate_normalized_vector,
)
from atlas.ive.similarity import (
    IdentityVectorSimilarity,
    compare_identity_vectors,
    identity_similarity_to_dict,
    validate_identity_similarity,
)

__all__ = [
    "IVE_VERSION",
    "VECTOR_FEATURES",
    "IDENTITY_GLOBAL_FEATURES",
    "PlanetFeatureVector",
    "NormalizedPlanetVector",
    "CompositePlanetVector",
    "IdentityVector",
    "PlanetRelationshipMatrix",
    "IdentityVectorSimilarity",
    "build_layer_vector_features",
    "build_planet_feature_vector",
    "build_raw_vectors_from_acf",
    "planet_feature_vector_to_dict",
    "normalized_planet_vector_to_dict",
    "composite_planet_vector_to_dict",
    "identity_vector_to_dict",
    "relationship_matrix_to_dict",
    "identity_similarity_to_dict",
    "validate_feature_vector",
    "validate_normalized_vector",
    "validate_composite_vector",
    "validate_identity_vector",
    "validate_relationship_matrix",
    "validate_identity_similarity",
    "DEFAULT_NORMALIZATION_MODE",
    "comparable_vectors",
    "normalize_feature_value",
    "normalize_planet_vector",
    "normalize_planet_vectors",
    "percentile_rank",
    "minmax_scale",
    "zscore_to_unit",
    "PLANET_ORDER",
    "ordered_planets",
    "build_composite_planet_vector",
    "build_composite_planet_vectors",
    "composite_vectors_to_feature_table",
    "build_identity_vector",
    "build_identity_global_features",
    "build_identity_quality",
    "build_identity_diagnostics",
    "ordered_planet_vectors",
    "build_planet_relationship_matrix",
    "compare_identity_vectors",
    "IVE_GRAPH_BRIDGE_VERSION",
    "GraphBackedIdentityVector",
    "build_graph_backed_identity_vector",
    "build_graph_ive_global_features",
    "graph_backed_identity_vector_to_dict",
]

from atlas.ive.graph_bridge import (
    IVE_GRAPH_BRIDGE_VERSION,
    GraphBackedIdentityVector,
    build_graph_backed_identity_vector,
    build_graph_ive_global_features,
    graph_backed_identity_vector_to_dict,
)
