"""Canonical macroeconomic series registry."""

from __future__ import annotations


MACRO_SERIES = {
    "cpi": {
        "series_id": "CPIAUCSL",
        "name": "Consumer Price Index",
        "category": "inflation",
        "frequency": "monthly",
        "transform": "year_over_year",
        "risk_direction": 1,
    },
    "core_cpi": {
        "series_id": "CPILFESL",
        "name": "Core Consumer Price Index",
        "category": "inflation",
        "frequency": "monthly",
        "transform": "year_over_year",
        "risk_direction": 1,
    },
    "ppi": {
        "series_id": "PPIACO",
        "name": "Producer Price Index",
        "category": "inflation",
        "frequency": "monthly",
        "transform": "year_over_year",
        "risk_direction": 1,
    },
    "unemployment": {
        "series_id": "UNRATE",
        "name": "Unemployment Rate",
        "category": "labor",
        "frequency": "monthly",
        "transform": "level",
        "risk_direction": 1,
    },
    "initial_claims": {
        "series_id": "ICSA",
        "name": "Initial Unemployment Claims",
        "category": "labor",
        "frequency": "weekly",
        "transform": "percent_change_13",
        "risk_direction": 1,
    },
    "fed_funds": {
        "series_id": "FEDFUNDS",
        "name": "Federal Funds Rate",
        "category": "monetary_policy",
        "frequency": "monthly",
        "transform": "level",
        "risk_direction": 1,
    },
    "treasury_3m": {
        "series_id": "DGS3MO",
        "name": "3-Month Treasury Yield",
        "category": "rates",
        "frequency": "daily",
        "transform": "level",
        "risk_direction": 1,
    },
    "treasury_2y": {
        "series_id": "DGS2",
        "name": "2-Year Treasury Yield",
        "category": "rates",
        "frequency": "daily",
        "transform": "level",
        "risk_direction": 1,
    },
    "treasury_10y": {
        "series_id": "DGS10",
        "name": "10-Year Treasury Yield",
        "category": "rates",
        "frequency": "daily",
        "transform": "level",
        "risk_direction": 1,
    },
    "dollar_index": {
        "series_id": "DTWEXBGS",
        "name": "Trade Weighted US Dollar Index",
        "category": "currency",
        "frequency": "daily",
        "transform": "percent_change_63",
        "risk_direction": 1,
    },
    "vix": {
        "series_id": "VIXCLS",
        "name": "CBOE Volatility Index",
        "category": "volatility",
        "frequency": "daily",
        "transform": "level",
        "risk_direction": 1,
    },
    "high_yield_spread": {
        "series_id": "BAMLH0A0HYM2",
        "name": "High Yield Option-Adjusted Spread",
        "category": "credit",
        "frequency": "daily",
        "transform": "level",
        "risk_direction": 1,
    },
    "financial_conditions": {
        "series_id": "NFCI",
        "name": "National Financial Conditions Index",
        "category": "financial_conditions",
        "frequency": "weekly",
        "transform": "level",
        "risk_direction": 1,
    },
    "fed_balance_sheet": {
        "series_id": "WALCL",
        "name": "Federal Reserve Total Assets",
        "category": "liquidity",
        "frequency": "weekly",
        "transform": "percent_change_52",
        "risk_direction": -1,
    },
    "money_supply": {
        "series_id": "M2SL",
        "name": "M2 Money Supply",
        "category": "liquidity",
        "frequency": "monthly",
        "transform": "year_over_year",
        "risk_direction": -1,
    },
}
