"""Portfolio Promotion Lab v2 walk-forward configuration."""

from __future__ import annotations


REBALANCE_FREQUENCY_DAYS = 14
MINIMUM_HISTORY_DAYS = 365
COVARIANCE_LOOKBACK_DAYS = 180
MINIMUM_COVARIANCE_DAYS = 45

MAX_SELECTED_ASSETS = 8
MAX_ASSET_WEIGHT = 0.40
BASELINE_CASH_FLOOR = 0.10
CANDIDATE_CASH_FLOOR = 0.20

TRANSACTION_COST_BPS = 10.0
ANNUALIZATION_DAYS = 365

PROMOTION_MIN_REBALANCES = 12
PROMOTION_MIN_NET_RETURN_ADVANTAGE = 0.03
PROMOTION_MIN_SHARPE_ADVANTAGE = 0.15
PROMOTION_MIN_DRAWDOWN_IMPROVEMENT = 0.02
PROMOTION_MIN_ROLLING_WIN_RATE = 0.60

MAX_CANDIDATE_DRAWDOWN = 0.40
MAX_CANDIDATE_TURNOVER = 1.00
MAX_CANDIDATE_VOLATILITY = 0.80

# Automatic production promotion is disabled until Atlas stores
# contemporaneous governance, macro, regime, and learning snapshots.
REQUIRE_HISTORICAL_GOVERNANCE_FOR_PRODUCTION = True
