"""Atlas nakshatra knowledge definitions."""

from __future__ import annotations

from typing import Any


NAKSHATRAS: dict[str, dict[str, Any]] = {
    "ashwini": {
        "name": "Ashwini",
        "ruler": "Ketu",
        "symbol": "Horse head",
        "theme": "initiation, speed, healing, rescue, and new beginnings",
        "description": "Ashwini emphasizes quick response, movement, restoration, instinct, and the impulse to begin before conditions are fully settled.",
        "strengths": ["speed", "healing impulse", "initiative", "adaptability"],
        "shadow": ["impatience", "restlessness", "unfinished starts"],
    },
    "bharani": {
        "name": "Bharani",
        "ruler": "Venus",
        "symbol": "Womb",
        "theme": "containment, transformation, endurance, responsibility, and creative pressure",
        "description": "Bharani emphasizes the power to carry, gestate, transform, and endure intense processes until they mature.",
        "strengths": ["endurance", "creative force", "responsibility", "depth"],
        "shadow": ["pressure accumulation", "intensity", "control struggles"],
    },
    "krittika": {
        "name": "Krittika",
        "ruler": "Sun",
        "symbol": "Blade",
        "theme": "purification, cutting through, discernment, heat, and refinement",
        "description": "Krittika emphasizes precision, purification, sharp perception, and the ability to separate what is useful from what is not.",
        "strengths": ["discernment", "clarity", "purification", "courage"],
        "shadow": ["harshness", "criticism", "impatience with weakness"],
    },
    "rohini": {
        "name": "Rohini",
        "ruler": "Moon",
        "symbol": "Ox cart",
        "theme": "growth, beauty, fertility, attraction, nourishment, and material development",
        "description": "Rohini emphasizes cultivation, attraction, sensuality, beauty, and the capacity to make things grow.",
        "strengths": ["nourishment", "beauty", "growth", "magnetism"],
        "shadow": ["attachment", "possessiveness", "indulgence"],
    },
    "mrigashira": {
        "name": "Mrigashira",
        "ruler": "Mars",
        "symbol": "Deer head",
        "theme": "searching, curiosity, movement, sensitivity, and discovery",
        "description": "Mrigashira emphasizes the searching mind, curiosity, exploration, and the restless pursuit of subtle information.",
        "strengths": ["curiosity", "sensitivity", "adaptability", "exploration"],
        "shadow": ["nervous searching", "inconsistency", "avoidance"],
    },
    "ardra": {
        "name": "Ardra",
        "ruler": "Rahu",
        "symbol": "Teardrop",
        "theme": "storm, disruption, grief, intensity, renewal, and radical clarity",
        "description": "Ardra emphasizes emotional storms, intellectual disruption, catharsis, and the clearing power of difficult truth.",
        "strengths": ["radical honesty", "renewal", "research intensity", "resilience"],
        "shadow": ["volatility", "destruction", "emotional turbulence"],
    },
    "punarvasu": {
        "name": "Punarvasu",
        "ruler": "Jupiter",
        "symbol": "Quiver of arrows",
        "theme": "return, renewal, restoration, optimism, and recurring growth",
        "description": "Punarvasu emphasizes restoration after difficulty, returning to essence, and recovering meaning through cycles.",
        "strengths": ["renewal", "optimism", "adaptation", "wisdom"],
        "shadow": ["repetition", "over-returning", "delayed closure"],
    },
    "pushya": {
        "name": "Pushya",
        "ruler": "Saturn",
        "symbol": "Cow udder",
        "theme": "nourishment, teaching, duty, protection, and disciplined care",
        "description": "Pushya emphasizes structured nourishment, protection, mentorship, and the responsibility to sustain life or knowledge.",
        "strengths": ["care", "discipline", "teaching", "protection"],
        "shadow": ["over-responsibility", "emotional withholding", "rigidity"],
    },
    "ashlesha": {
        "name": "Ashlesha",
        "ruler": "Mercury",
        "symbol": "Serpent",
        "theme": "binding, psychology, hidden intelligence, persuasion, and entanglement",
        "description": "Ashlesha emphasizes subtle perception, psychological intelligence, influence, secrecy, and the power of binding attention.",
        "strengths": ["psychological insight", "strategy", "subtle perception", "persuasion"],
        "shadow": ["manipulation", "entanglement", "suspicion"],
    },
    "magha": {
        "name": "Magha",
        "ruler": "Ketu",
        "symbol": "Throne",
        "theme": "ancestry, authority, lineage, inheritance, and dignity",
        "description": "Magha emphasizes ancestral power, inherited status, symbolic authority, and the responsibility of occupying a seat of influence.",
        "strengths": ["dignity", "leadership", "lineage awareness", "command"],
        "shadow": ["pride", "status fixation", "rigid hierarchy"],
    },
    "purva_phalguni": {
        "name": "Purva Phalguni",
        "ruler": "Venus",
        "symbol": "Front legs of a bed",
        "theme": "pleasure, creativity, romance, rest, beauty, and social enjoyment",
        "description": "Purva Phalguni emphasizes creative enjoyment, attraction, artistic expression, celebration, and the restoration that comes through pleasure.",
        "strengths": ["creativity", "charm", "pleasure", "social warmth"],
        "shadow": ["indulgence", "avoidance of duty", "vanity"],
    },
    "uttara_phalguni": {
        "name": "Uttara Phalguni",
        "ruler": "Sun",
        "symbol": "Back legs of a bed",
        "theme": "contracts, loyalty, patronage, duty, and lasting bonds",
        "description": "Uttara Phalguni emphasizes sustainable agreements, service through commitment, social responsibility, and the maturation of creative bonds.",
        "strengths": ["loyalty", "reliability", "support", "honor"],
        "shadow": ["overcommitment", "status dependency", "rigid obligation"],
    },
    "hasta": {
        "name": "Hasta",
        "ruler": "Moon",
        "symbol": "Hand",
        "theme": "skill, craft, manifestation, dexterity, and practical intelligence",
        "description": "Hasta emphasizes hands-on intelligence, craft, skillful execution, humor, and the power to make ideas tangible.",
        "strengths": ["craft", "dexterity", "practical skill", "manifestation"],
        "shadow": ["trickery", "control through skill", "restlessness"],
    },
    "chitra": {
        "name": "Chitra",
        "ruler": "Mars",
        "symbol": "Jewel",
        "theme": "design, beauty, construction, brilliance, and refinement",
        "description": "Chitra emphasizes architecture, aesthetics, technical brilliance, and the transformation of raw material into striking form.",
        "strengths": ["design", "beauty", "technical skill", "vision"],
        "shadow": ["appearance fixation", "perfectionism", "vanity"],
    },
    "swati": {
        "name": "Swati",
        "ruler": "Rahu",
        "symbol": "Young sprout in wind",
        "theme": "independence, movement, trade, flexibility, and self-direction",
        "description": "Swati emphasizes autonomy, adaptability, wind-like movement, commerce, and the freedom to develop independently.",
        "strengths": ["independence", "adaptability", "commerce", "mobility"],
        "shadow": ["rootlessness", "scattering", "avoidance of commitment"],
    },
    "vishakha": {
        "name": "Vishakha",
        "ruler": "Jupiter",
        "symbol": "Triumphal arch",
        "theme": "ambition, focus, achievement, devotion, and dual pathways",
        "description": "Vishakha emphasizes determined pursuit, achievement through focus, and the intensity required to reach a chosen goal.",
        "strengths": ["focus", "ambition", "devotion", "achievement"],
        "shadow": ["obsession", "comparison", "divided desire"],
    },
    "anuradha": {
        "name": "Anuradha",
        "ruler": "Saturn",
        "symbol": "Lotus",
        "theme": "friendship, devotion, discipline, networks, and emotional loyalty",
        "description": "Anuradha emphasizes loyal bonds, disciplined devotion, group alignment, and the ability to grow through friendship and shared purpose.",
        "strengths": ["loyalty", "friendship", "devotion", "discipline"],
        "shadow": ["dependency", "emotional suppression", "group pressure"],
    },
    "jyeshtha": {
        "name": "Jyeshtha",
        "ruler": "Mercury",
        "symbol": "Earring",
        "theme": "seniority, protection, power, strategy, and responsibility",
        "description": "Jyeshtha emphasizes seniority, strategic intelligence, protection, authority under pressure, and the burden of responsibility.",
        "strengths": ["strategy", "protection", "authority", "resourcefulness"],
        "shadow": ["control", "jealousy", "defensiveness"],
    },
    "mula": {
        "name": "Mula",
        "ruler": "Ketu",
        "symbol": "Roots tied together",
        "theme": "roots, investigation, destruction, truth, and radical origin-seeking",
        "description": "Mula emphasizes digging to the root, dismantling illusions, confronting origins, and seeking foundational truth.",
        "strengths": ["truth-seeking", "research", "radical clarity", "root analysis"],
        "shadow": ["destruction", "severity", "uprooting without rebuilding"],
    },
    "purva_ashadha": {
        "name": "Purva Ashadha",
        "ruler": "Venus",
        "symbol": "Fan",
        "theme": "invigoration, persuasion, declaration, cleansing, and conviction",
        "description": "Purva Ashadha emphasizes persuasive force, conviction, inspiration, purification, and the confidence to declare a vision.",
        "strengths": ["persuasion", "conviction", "inspiration", "resilience"],
        "shadow": ["dogmatism", "overconfidence", "refusal to yield"],
    },
    "uttara_ashadha": {
        "name": "Uttara Ashadha",
        "ruler": "Sun",
        "symbol": "Elephant tusk",
        "theme": "victory, endurance, universal principles, leadership, and final achievement",
        "description": "Uttara Ashadha emphasizes lasting victory, principled action, patience, leadership, and success through sustained alignment.",
        "strengths": ["endurance", "principle", "leadership", "stability"],
        "shadow": ["rigidity", "moral superiority", "slow adaptation"],
    },
    "shravana": {
        "name": "Shravana",
        "ruler": "Moon",
        "symbol": "Ear",
        "theme": "listening, learning, transmission, memory, and sacred knowledge",
        "description": "Shravana emphasizes listening, receiving, teaching, preserving knowledge, and transmitting meaning through attention.",
        "strengths": ["listening", "learning", "teaching", "memory"],
        "shadow": ["gossip", "dependency on authority", "over-absorption"],
    },
    "dhanishta": {
        "name": "Dhanishta",
        "ruler": "Mars",
        "symbol": "Drum",
        "theme": "rhythm, wealth, performance, timing, and group coordination",
        "description": "Dhanishta emphasizes rhythm, timing, prosperity, music, social coordination, and the ability to move with collective momentum.",
        "strengths": ["rhythm", "timing", "coordination", "prosperity"],
        "shadow": ["status pressure", "restlessness", "performative identity"],
    },
    "shatabhisha": {
        "name": "Shatabhisha",
        "ruler": "Rahu",
        "symbol": "Circle of healing",
        "theme": "healing, secrecy, systems, isolation, and radical analysis",
        "description": "Shatabhisha emphasizes systemic analysis, hidden healing, technological or unconventional intelligence, and the need for solitude.",
        "strengths": ["systems analysis", "healing", "independence", "research"],
        "shadow": ["isolation", "detachment", "obsessive analysis"],
    },
    "purva_bhadrapada": {
        "name": "Purva Bhadrapada",
        "ruler": "Jupiter",
        "symbol": "Front legs of funeral cot",
        "theme": "intensity, vows, transformation, austerity, and spiritual fire",
        "description": "Purva Bhadrapada emphasizes intensity, devotion to ideals, purification through extremes, and transformative commitment.",
        "strengths": ["commitment", "intensity", "spiritual force", "vision"],
        "shadow": ["extremism", "severity", "fanaticism"],
    },
    "uttara_bhadrapada": {
        "name": "Uttara Bhadrapada",
        "ruler": "Saturn",
        "symbol": "Back legs of funeral cot",
        "theme": "depth, stillness, endurance, hidden wisdom, and inner stability",
        "description": "Uttara Bhadrapada emphasizes deep patience, hidden knowledge, restraint, compassion, and the stability beneath emotional waters.",
        "strengths": ["depth", "stability", "patience", "wisdom"],
        "shadow": ["inertia", "emotional heaviness", "withdrawal"],
    },
    "revati": {
        "name": "Revati",
        "ruler": "Mercury",
        "symbol": "Fish",
        "theme": "completion, guidance, protection, travel, and safe passage",
        "description": "Revati emphasizes endings, guidance, protection, compassion, safe movement, and the ability to shepherd transitions.",
        "strengths": ["guidance", "compassion", "completion", "adaptability"],
        "shadow": ["drift", "over-accommodation", "escapism"],
    },
}


ALIASES = {
    "aswini": "ashwini",
    "asvini": "ashwini",
    "poorva phalguni": "purva_phalguni",
    "purva phalguni": "purva_phalguni",
    "uttara phalguni": "uttara_phalguni",
    "chitraa": "chitra",
    "visakha": "vishakha",
    "jyestha": "jyeshtha",
    "moola": "mula",
    "purva ashadha": "purva_ashadha",
    "poorva ashadha": "purva_ashadha",
    "uttara ashadha": "uttara_ashadha",
    "sravana": "shravana",
    "sravana": "shravana",
    "satabhisha": "shatabhisha",
    "shatabisha": "shatabhisha",
    "purva bhadrapada": "purva_bhadrapada",
    "poorva bhadrapada": "purva_bhadrapada",
    "uttara bhadrapada": "uttara_bhadrapada",
}


def normalize_nakshatra(value: str) -> str:
    """Normalize nakshatra name."""
    key = str(value or "").strip().lower().replace("-", " ").replace("_", " ")
    return ALIASES.get(key, key.replace(" ", "_"))


def get_nakshatra(value: str) -> dict[str, Any]:
    """Return nakshatra knowledge."""
    key = normalize_nakshatra(value)
    return NAKSHATRAS.get(
        key,
        {
            "name": str(value).title(),
            "ruler": "",
            "symbol": "",
            "theme": "",
            "description": "This nakshatra is present in the compiled temporal layer.",
            "strengths": [],
            "shadow": [],
        },
    )
