"""Canonical Atlas Compiler source registry."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class SourceSpec:
    """One compiler input artifact."""

    component_id: str
    section: str
    path: Path
    source_type: str
    required: bool = True


SOURCE_SPECS = [
    SourceSpec(
        component_id="alpha_engines",
        section="alpha",
        path=Path(
            "output/investment_alpha_engines/"
            "alpha_engine_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="historical_alpha_engines",
        section="alpha",
        path=Path(
            "output/investment_alpha_engines/"
            "historical_alpha_engine_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="historical_alpha_validation",
        section="alpha",
        path=Path(
            "output/investment_alpha_engines/"
            "historical_alpha_engine_validation.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="macro_intelligence",
        section="market_context",
        path=Path(
            "output/investment_macro_intelligence/"
            "macro_intelligence_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="regime_intelligence",
        section="market_context",
        path=Path(
            "output/investment_regime_intelligence/"
            "regime_intelligence_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="macro_regime_fusion",
        section="market_context",
        path=Path(
            "output/investment_macro_regime_fusion/"
            "macro_regime_fusion_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="alpha_research_lab",
        section="research",
        path=Path(
            "output/investment_alpha_research_lab/"
            "alpha_research_lab_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="alpha_ensemble",
        section="ensemble",
        path=Path(
            "output/investment_alpha_ensemble/"
            "alpha_ensemble_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="ensemble_intelligence_v7",
        section="ensemble",
        path=Path(
            "output/investment_alpha_ensemble/"
            "ensemble_v7_audit.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="learning_engine",
        section="learning",
        path=Path(
            "output/investment_learning/"
            "learning_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="governance_snapshots",
        section="governance",
        path=Path(
            "output/investment_governance_snapshots/"
            "governance_snapshots_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="meta_research",
        section="research",
        path=Path(
            "output/investment_meta_research/"
            "meta_research_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="hypothesis_validation",
        section="research",
        path=Path(
            "output/investment_hypothesis_validation/"
            "hypothesis_validation_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="validated_variant_registry",
        section="variants",
        path=Path(
            "output/investment_validated_variants/"
            "validated_variant_registry_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="variant_review_board",
        section="variants",
        path=Path(
            "output/investment_variant_review/"
            "variant_review_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="variant_decision_ledger",
        section="variants",
        path=Path(
            "output/investment_variant_decisions/"
            "variant_decision_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="variant_implementation_planner",
        section="variants",
        path=Path(
            "output/investment_variant_implementation_planner/"
            "variant_implementation_planner_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="portfolio_optimizer",
        section="portfolio",
        path=Path(
            "output/investment_portfolio_optimizer/"
            "portfolio_optimizer_report.json"
        ),
        source_type="json",
    ),
    SourceSpec(
        component_id="portfolio_promotion_lab_v1",
        section="portfolio",
        path=Path(
            "output/investment_portfolio_promotion_lab/"
            "portfolio_promotion_report.json"
        ),
        source_type="json",
        required=False,
    ),
    SourceSpec(
        component_id="portfolio_promotion_lab_v2",
        section="portfolio",
        path=Path(
            "output/investment_portfolio_promotion_lab_v2/"
            "portfolio_promotion_v2_report.json"
        ),
        source_type="json",
        required=False,
    ),
    SourceSpec(
        component_id="variant_decision_ledger_table",
        section="variants",
        path=Path(
            "output/investment_variant_decisions/"
            "variant_decision_ledger.csv"
        ),
        source_type="csv",
    ),
    SourceSpec(
        component_id="implementation_queue",
        section="variants",
        path=Path(
            "output/investment_variant_decisions/"
            "implementation_queue.csv"
        ),
        source_type="csv",
    ),
    SourceSpec(
        component_id="optimized_portfolio",
        section="portfolio",
        path=Path(
            "output/investment_portfolio_optimizer/"
            "optimized_portfolio.csv"
        ),
        source_type="csv",
    ),
]

