
"""Trade Safety Governor limits."""

from __future__ import annotations

MAX_TOTAL_EXPOSURE = 0.60
MAX_SINGLE_ASSET_EXPOSURE = 0.30
MIN_CASH_WEIGHT = 0.25
MAX_WAITING_WEIGHT = 0.15
MAX_COST_DRAG = 0.0025
MAX_ORDER_COUNT = 5
ALLOW_SHORTS = False
ALLOW_LIVE_TRADING = False
